apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Workflow Trigger Parameters
on:
  workflow_dispatch:
    inputs:
      stringIn:
        type: string
        default: String input value
        required: true
        description: Input string
      pickList:
        type: choice
        options:
          - abc
          - def
          - ghi
        default: abc
        description: Pick list description
      bool:
        type: boolean
        default: true
        description: A Boolean entry
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "${{ inputs.stringIn }}"
          echo "${{ inputs.pickList }}"
